# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
######################################################
service: whatsapp-webhooks
frameworkVersion: '2 || 3'

provider:
 name: aws
 timeout: 900
 runtime: nodejs14.x
 # lambdaHashingVersion: '20201221'
 region: us-east-1 # N.Viriginia
 iamRoleStatements:
   - Effect: "Allow"
     Action:
     - dynamodb:Query
     - dynamodb:Scan
     - dynamodb:GetItem
     - dynamodb:PutItem
     - dynamodb:UpdateItem
     - dynamodb:DeleteItem
     Resource: arn:aws:dynamodb:us-east-1:111111111111:table/${self:provider.environment.REVIEW_TABLE}
 environment:
   TOKEN: ###
   PRIVATE_API_TOKEN: ###
   REVIEW_TABLE: reviews
   TOKEN_TABLE: whatsappToken

package:
  patterns:
    - '!whatsapp-bot-worker/**'

plugins:
 - serverless-offline
 - serverless-dynamodb-local

functions:
 app:
   handler: handler.handler
   events:
     - http: 
          path: /
          method: ANY
          cors:
            - enabled: true
            - origin: 'https://www.ZZZ.com'
     - http: 
          path: /{proxy+}
          method: ANY
          cors:
           - enabled: true
           - origin: 'https://www.ZZZ.com'
 nextDayJob:
   handler: batch/check-next-day-message.run
   events:
     - schedule: rate(5 minutes) # change this rate to increase or decrease checking interval for next day message
 reminderJob:
   handler: batch/check-recipient.run
   events:
     - schedule: rate(5 minutes) # change this rate to increase or decrease checking interval for reminder

resources:
 Resources:
   ReviewsTable:
     Type: 'AWS::DynamoDB::Table'
     Properties:
       TableName: ${self:provider.environment.REVIEW_TABLE}
       AttributeDefinitions:
         - AttributeName: phonenumber
           AttributeType: S
       KeySchema:
         - AttributeName: phonenumber
           KeyType: HASH
       ProvisionedThroughput:
         ReadCapacityUnits: 1
         WriteCapacityUnits: 1
######################################################